import { sendMsg } from "./print";

/**
 * Generates the HTML content to be sent to the client's browser.
 *
 * This function returns a complete HTML page structure that includes:
 * - A `<pre>` tag displaying the welcome message generated by `sendMsg()`.
 * - A `<script>` tag that animates the text color between blue, red, yellow, and green every second.
 *
 * This function is **specifically used** to send the welcome message to the client side,
 * and should not be used else where.
 *
 */
export const sendContent = () => `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Welcome to Nexu</title>
      <style>
        body {
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
          background-color: #000;
          margin: 0;
          width: 100%;
        }
        .animated-text {
          
        }
      </style>
    </head>
    <body>
      <pre class="animated-text">${sendMsg().send}</pre>
      <script>
        const colors = ["blue", "red", "yellow", "green"];
        let index = 0;
        const element = document.querySelector(".animated-text");

        function animateColors() {
          element.style.color = colors[index];
          index = (index + 1) % colors.length;
        }

        setInterval(animateColors, 1000);
      </script>
    </body>
    </html>
  `;
